### ISSUE TITLE
Tradução do campaign.json

### ISSUE THREAD

**Issue by lucasmedeiros** [rafaelcastrocouto/foda#2]
Olá, me interessei pelo projeto, encontrei por acaso em um post sobre repositórios brasileiros que necessitam de ajuda nessa Hacktoberfest. Achei muito interessante o jogo, e fui dar uma olhada no código a partir do meu fork.

Fiquei com uma dúvida: nas pastas que contêm as traduções do jogo não possuem o `campaign.json`, que possui termos "traduzíveis". Gostaria de saber se é pretendido fazer a tradução desse arquivo e, caso sim, se eu poderia pegar essa task.

**Comment by rafaelcastrocouto** [comment]
Oi lucas, blz? Obrigado pelo elogio e pelo interesse!

Sim, o arquivo `campaign.json` que contém as strings para a tela da campanha (js/states/campaign.js)
precisa ser traduzido, e vc pode pegar essa tarefa, seria uma ótima contribuição. 👍

Esses arquivos são carregados durante o "loading state" e após termos todas as traduções, basta adicionar um argumento `true` [nessa linha](https://github.com/rafaelcastrocouto/foda/blob/master/client/js/states/loading.js#L18) para a tradução acontecer automaticamente.

**Comment by lucasmedeiros** [comment]
Show, vou fazer hoje então! :smile:

**Comment by lucasmedeiros** [comment]
Fiquei com uma dúvida agora: colocar o argumento `true` na linha do `game.states.loading.json`, caso a tradução do arquivo exista apenas em PT-BR e não nas outras linguagens, caso uma dessas linguagens fosse selecionada, ocorreria algum problema?

**Comment by rafaelcastrocouto** [comment]
Sim haveria um erro por não encontrar o arquivo que o código presume estar lá. Mas vc pode fazer isso na sua máquina só para testar, sem problemas.
Não se preocupe, eu traduzo para as outras linguagens com o google e depois mando para as pessoas que ajudaram em cada tradução para os ajustes finais.
