### ISSUE TITLE
Bug report#1

### ISSUE THREAD

**Issue by DStarsthy** [rafaelcastrocouto/foda#22]
**Describe the bug**
Match ending indefinitely on enemy turn.

**To Reproduce**
1. End own turn and wait for enemy turn
2. They pull out a passive card
3. Error happens

**Expected behavior**
Match goes on like normal with the enemy card in question getting the passive buff

**Screenshots**
![image](https://user-images.githubusercontent.com/83871848/117549521-db46a880-b008-11eb-949d-0593b056825e.png)
https://siasky.net/AADEioUCPjvi7lZvclJZCPsJ2GIvnYJPN-LIW5TgC8t_XQ

**Versions (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 0.5.58

**Comment by rafaelcastrocouto** [comment]
Is this bug still happening? It should've been fixed by https://github.com/rafaelcastrocouto/foda/commit/ec49ff02fd6a7c47b2bfd1b6b10507d66baeb513

**Comment by DStarsthy** [comment]
Yes, at least on the first mission.

**Comment by DStarsthy** [comment]
Now it happens on the second mission
![image](https://user-images.githubusercontent.com/83871848/118184522-7248a180-b409-11eb-932a-330fdf52999f.png)

**Comment by rafaelcastrocouto** [comment]
I think I've solved this one with the last AI fix ... can you confirm plz?

**Comment by DStarsthy** [comment]
Yes, I can do the campaign fully now
