### ISSUE TITLE
Starting with 40 gold

### ISSUE THREAD

**Issue by DStarsthy** [rafaelcastrocouto/foda#23]
**Describe the bug**
At the first mission of the campaign, I start out with 40 gold.

**To Reproduce**
1. Start the first campaign mission and wait for the start of one's turn

**Expected behavior**
Get 400 to start along with the 40 gold per turn.

**Screenshots**
![image](https://user-images.githubusercontent.com/83871848/118184763-c05da500-b409-11eb-885a-8130f482e707.png)

**Versions (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 0.5.59

**Additional context**
This happens with any group of heroes in one's team.
Once the first mission is over, this bug doesn't occur on following missions, including the first mission.

**Comment by rafaelcastrocouto** [comment]
Fixed by https://github.com/rafaelcastrocouto/foda/commit/bdb25905020b0793e87b61e8dbf6591787e0ff13
Could you please confirm?

**Comment by DStarsthy** [comment]
Yup, fixed.
