### ISSUE TITLE
Can't move to certain squares

### ISSUE THREAD

**Issue by DStarsthy** [rafaelcastrocouto/foda#25]
**Describe the bug**
Can't move to certain squares where units once stood.

**To Reproduce**
1. Kill a hero unit
2. Wait for your turn again
3. Can't walk on their zone

**Expected behavior**
Once the space is cleared, I can walk where the unit once stood.

**Screenshots**
![image](https://user-images.githubusercontent.com/83871848/118294474-bfc81b80-b4a8-11eb-8e13-15bdc2cc3384.png)
![image](https://user-images.githubusercontent.com/83871848/118294627-e8501580-b4a8-11eb-8030-abb074a25280.png)

**Versions (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 0.5.61

**Additional context**
This seems to happen later in the game only.

**Comment by rafaelcastrocouto** [comment]
Could not replicate this one yet ... gonna keep trying and if it happens again plz give me some extra context.
