### ISSUE TITLE
Remove bundle from git repo (?)

### ISSUE THREAD

**Issue by aurium** [rafaelcastrocouto/foda#5]
Hi Rafael,

I did remove `client/bundle/*` from git because it stores (kind of)useless (and very big) diffs, that difficults to scroll `git diff` on console. Then you recover `client/bundle/*` to make it work on heroku (i forgot that). I believe you can solve this running the grunt tasks needed to build the bundle before the `node server.js` in the start script.

Add to `Gruntfile.js`:
```js
grunt.registerTask('bundle', ['cssmin', 'uglify', 'concat', 'clean']);
```
Add do `package.json`:
```json
{
  ...
  "scripts": {
    "start": "grunt bundle && node server.js",
    ...
  }
...
}
```

I can't test, but i believe it is enough. It is ok to you?

**Comment by rafaelcastrocouto** [comment]
Don't worry, I'll remove it again as you did. I do agree that it makes bad diffs and shouldn't be there. 
I was struggling to fix my heroku deploy cuz I was getting an wrong nodejs version error log on the front end service. The real log showed me that the electron build was the real cause of the problem. So I'll just add it back to the gitignore

**Comment by rafaelcastrocouto** [comment]
Closed by https://github.com/rafaelcastrocouto/foda/commit/e1e77c17a502b8f6a742f22c60dcf99c37ea27df
