### ISSUE TITLE
Uncaught TypeError: Cannot set property 'campaign' of undefined

### ISSUE THREAD

**Issue by Nicholaiii** [rafaelcastrocouto/foda#8]
**Describe the bug**
Game refuses to start due to this error.
```
Uncaught TypeError: Cannot set property 'campaign' of undefined
    at game.min.js:15
```

**To Reproduce**
Open [the game](https://foda-app.herokuapp.com/)

**Expected behavior**
Gameplay

**Versions (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 77.0.3865.120 64-bit

**Comment by rafaelcastrocouto** [comment]
Hey, thanks for reporting!
Here are a few possible solutions:
1 - Clear you browser cache (if you are in mobile clear the browsing history)
2 - Open the game in debug mode https://foda-app.herokuapp.com/debug.html and check if the error persists.

**Comment by Nicholaiii** [comment]
Clearing cache didn't work, but debug mode did, with nothing in the console at all.
I also experience this error in non-debug mode:
```
jQuery.Deferred exception: Cannot read property 'extendjQuery' of undefined TypeError: Cannot read property 'extendjQuery' of undefined
```

**Comment by rafaelcastrocouto** [comment]
Confirmed bug, fixing it right now!

**Comment by rafaelcastrocouto** [comment]
Fixed, please confirm it's fixed in order to close this issue!

**Comment by Nicholaiii** [comment]
On a clean cache it works now, but it occurs on subsequent loadas.

**Comment by rafaelcastrocouto** [comment]
great, now I just need to update the game version!

**Comment by rafaelcastrocouto** [comment]
fixed in https://github.com/rafaelcastrocouto/foda/commit/32ee2bddde3da167a7162f32cf1088a0b3bd9307
